Repository mongeul/mongeulmongeul, pull requests merged in 2025-05, with the labels that each got.

#140 Feature/24 login
  mongeul/src/app/login/google/callback/page.tsx
  mongeul/src/app/login/kakao/callback/page.tsx
  mongeul/src/app/login/naver/callback/page.tsx
  mongeul/src/app/login/page.tsx
  mongeul/src/components/auth/atoms/RedirectHandler.tsx
  mongeul/src/components/auth/molecules/SocialLoginButtons.tsx
  mongeul/src/components/layout/ClientLayout.tsx
  mongeul/src/components/setting/molecules/LogOutModalContent.tsx
  mongeul/src/components/setting/molecules/WithdrawModalContent.tsx
  mongeul/src/components/setting/templates/LogOutTemplates.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/auth.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#141 Feature/24 login
  mongeul/src/app/login/google/callback/GoogleCallbackInner.tsx
  mongeul/src/app/login/google/callback/page.tsx
  mongeul/src/app/login/kakao/callback/KakaoCallbackInner.tsx
  mongeul/src/app/login/kakao/callback/page.tsx
  mongeul/src/app/login/naver/callback/NaverCallbackInner.tsx
  mongeul/src/app/login/naver/callback/page.tsx
Labels: 🌈 FE, ♻️ refactoring

#142 design: 달력 크기 고정
  mongeul/src/components/calendar/atoms/CalendarDate.tsx
  mongeul/src/components/calendar/molecules/CalendarGrid.tsx
  mongeul/src/components/calendar/organisms/Calendar.tsx
  mongeul/src/components/diary/organisms/DiaryPreview.tsx
Labels: 🌈 FE, ♻️ refactoring

#144 refactor: 공유일기템플릿 수정
  mongeul/src/components/shared-diary/templates/SharedDiaryTemplate.tsx
Labels: 🌈 FE, ♻️ refactoring

#145 Feature/24 login
  mongeul/src/components/layout/SearchParamsProvider.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryDeleteButton.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryUpdateButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
Labels: 🌈 FE, ♻️ refactoring

#146 fix: 이모지 상태 적용
  mongeul/src/components/feed/atoms/FeedEmojiCountButton.tsx
  mongeul/src/components/feed/atoms/FeedListItem.tsx
  mongeul/src/components/feed/molecules/FeedEmojiGroup.tsx
  mongeul/src/components/feed/molecules/FeedList.tsx
Labels: 🌈 FE, 🐛 bug
