Repository mongeul/mongeulmongeul, pull requests merged in 2025-02, with the labels that each got.

#11 Feature/2 comment
  mongeul/src/main/java/com/specup/mongeul/domain/comment/controller/CommentController.java
  mongeul/src/main/java/com/specup/mongeul/domain/comment/dto/request/CommentRequest.java
  mongeul/src/main/java/com/specup/mongeul/domain/comment/dto/response/CommentResponse.java
  mongeul/src/main/java/com/specup/mongeul/domain/comment/entity/Comment.java
  mongeul/src/main/java/com/specup/mongeul/domain/comment/repository/CommentRepository.java
  mongeul/src/main/java/com/specup/mongeul/domain/comment/service/CommentService.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/controller/DiaryController.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/dto/response/DiaryResponse.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/entity/Diary.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/repository/DiaryRepository.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/service/DiaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/user/entity/User.java
  mongeul/src/main/java/com/specup/mongeul/global/error/ErrorCode.java
  mongeul/src/test/java/mongeul/comment/api/CommentApiTest.java
  mongeul/src/test/java/mongeul/diary/api/DiaryApiTest.java
Labels: 🔥 BE, 💫 feat

#22 Feature/18 navbar
  mongeul/next.config.ts
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/public/fonts/GowunDodum-Regular.ttf
  mongeul/public/fonts/SUIT-Variable.woff2
  mongeul/src/app/diary/page.tsx
  mongeul/src/app/feed/page.tsx
  mongeul/src/app/globals.css
  mongeul/src/app/layout.tsx
  mongeul/src/app/notification/page.tsx
  mongeul/src/app/page.tsx
  mongeul/src/app/setting/@detail/font/page.tsx
  mongeul/src/app/setting/@detail/page.tsx
  mongeul/src/app/setting/@detail/theme/page.tsx
  mongeul/src/app/setting/default.tsx
  mongeul/src/app/setting/layout.tsx
  mongeul/src/app/setting/page.tsx
  mongeul/src/app/shared-diary/page.tsx
  mongeul/src/assets/icons/diary.svg
  mongeul/src/assets/icons/feed.svg
  mongeul/src/assets/icons/notification.svg
  mongeul/src/assets/icons/setting.svg
  mongeul/src/assets/icons/shared-diary.svg
  mongeul/src/assets/icons/write.svg
  mongeul/src/components/Header.tsx
  mongeul/src/components/NavBar.tsx
  mongeul/src/components/ParellelLayout.tsx
  mongeul/src/components/WriteButton.tsx
  mongeul/src/context/ThemeContext.tsx
  mongeul/src/lib/theme.ts
  mongeul/tailwind.config.ts
Labels: 🌈 FE, 💫 feat

#30 Feature/25 writediary
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/app/api/diary/create-diary/route.ts
  mongeul/src/app/api/diary/read-diary/route.ts
  mongeul/src/app/layout.tsx
  mongeul/src/app/write-diary/page.tsx
  mongeul/src/assets/icons/close.svg
  mongeul/src/assets/icons/feelings.svg
  mongeul/src/assets/icons/happy.svg
  mongeul/src/assets/icons/locked.svg
  mongeul/src/assets/icons/public.svg
  mongeul/src/assets/icons/unlocked.svg
  mongeul/src/assets/icons/weather.svg
  mongeul/src/components/ClientLayout.tsx
  mongeul/src/components/DefaultLayout.tsx
  mongeul/src/components/ParellelLayout.tsx
  mongeul/src/components/WriteButton.tsx
  mongeul/src/components/button.tsx
  mongeul/src/components/card.tsx
  mongeul/src/components/write-diary/WriteButtonDetail.tsx
  mongeul/src/components/write-diary/atoms/Input.tsx
  mongeul/src/components/write-diary/atoms/MobileModal.tsx
  mongeul/src/components/write-diary/atoms/RoundIcon.tsx
  mongeul/src/components/write-diary/atoms/Textarea.tsx
  mongeul/src/components/write-diary/atoms/WebModal.tsx
  mongeul/src/components/write-diary/molecules/DisclosureSelect.tsx
  mongeul/src/components/write-diary/molecules/FeelingsSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/organisms/ContentCard.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/IconCard.tsx
  mongeul/src/components/write-diary/organisms/TitleCard.tsx
  mongeul/src/lib/api/diary.ts
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/store.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/utils/formatDate.ts
Labels: 🌈 FE, 💫 feat

#31 rename: 컴포넌트 폴더 구조 변경
  mongeul/src/app/layout.tsx
  mongeul/src/app/setting/layout.tsx
  mongeul/src/app/write-diary/page.tsx
  mongeul/src/components/common/atoms/Button.tsx
  mongeul/src/components/common/atoms/Card.tsx
  mongeul/src/components/common/atoms/Input.tsx
  mongeul/src/components/common/atoms/MobileModal.tsx
  mongeul/src/components/common/atoms/RoundIcon.tsx
  mongeul/src/components/common/atoms/Textarea.tsx
  mongeul/src/components/common/atoms/WebModal.tsx
  mongeul/src/components/header/orgamisms/Header.tsx
  mongeul/src/components/layout/ClientLayout.tsx
  mongeul/src/components/layout/DefaultLayout.tsx
  mongeul/src/components/layout/ParellelLayout.tsx
  mongeul/src/components/navbar/atoms/WriteButton.tsx
  mongeul/src/components/navbar/molecules/WriteButtonDetail.tsx
  mongeul/src/components/navbar/organisms/NavBar.tsx
  mongeul/src/components/write-diary/molecules/DisclosureSelect.tsx
  mongeul/src/components/write-diary/molecules/FeelingsSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/organisms/ContentCard.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/IconCard.tsx
  mongeul/src/components/write-diary/organisms/TitleCard.tsx
Labels: 🌈 FE

#38 Feature/26 paintingdiary
  mongeul/next.config.ts
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/app/globals.css
  mongeul/src/app/layout.tsx
  mongeul/src/app/write-diary/drawing/page.tsx
  mongeul/src/app/write-diary/layout.tsx
  mongeul/src/app/write-diary/page.tsx
  mongeul/src/assets/icons/date.svg
  mongeul/src/assets/icons/eraser.svg
  mongeul/src/assets/icons/palette.svg
  mongeul/src/assets/icons/pen.svg
  mongeul/src/assets/icons/pencil.svg
  mongeul/src/assets/icons/redo.svg
  mongeul/src/assets/icons/trash.svg
  mongeul/src/assets/icons/undo.svg
  mongeul/src/components/common/atoms/Card.tsx
  mongeul/src/components/common/atoms/WebModal.tsx
  mongeul/src/components/navbar/organisms/NavBar.tsx
  mongeul/src/components/write-diary/atoms/BrushSelectButton.tsx
  mongeul/src/components/write-diary/atoms/BrushSizeButton.tsx
  mongeul/src/components/write-diary/atoms/ColorButton.tsx
  mongeul/src/components/write-diary/atoms/UndoRedoButton.tsx
  mongeul/src/components/write-diary/molecules/BrushSelectPalette.tsx
  mongeul/src/components/write-diary/molecules/BrushSizePalette.tsx
  mongeul/src/components/write-diary/molecules/ColorPalette.tsx
  mongeul/src/components/write-diary/molecules/UndoRedoButtons.tsx
  mongeul/src/components/write-diary/organisms/Canvas.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/DrawingCard.tsx
  mongeul/src/components/write-diary/organisms/DrawingToolCard.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/templates/DrawingForm.tsx
  mongeul/src/components/write-diary/templates/WriteForm.tsx
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/drawingSlice.ts
  mongeul/src/store/store.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/types/drawingTypes.ts
  mongeul/tailwind.config.ts
Labels: 🌈 FE, 💫 feat

#39 Feature/32 sharediary
  mongeul/src/app/api/auth/kakao/route.ts
  mongeul/src/app/auth/login/page.tsx
  mongeul/src/app/auth/nickname-setting/page.tsx
  mongeul/src/app/shared-diary/page.tsx
  mongeul/src/assets/icons/code.svg
  mongeul/src/assets/icons/friend.svg
  mongeul/src/assets/icons/friend2.svg
  mongeul/src/assets/icons/google.png
  mongeul/src/assets/icons/kakao.png
  mongeul/src/assets/icons/menudot.svg
  mongeul/src/assets/icons/naver.png
  mongeul/src/components/auth/atoms/Divider.tsx
  mongeul/src/components/auth/atoms/SocialLoginButton.tsx
  mongeul/src/components/auth/molecules/SocialLoginButtons.tsx
  mongeul/src/components/auth/organisms/LoginSection.tsx
  mongeul/src/components/common/atoms/Button.tsx
  mongeul/src/components/shared-diary/atoms/DiaryStats.tsx
  mongeul/src/components/shared-diary/atoms/NicknameBadge.tsx
  mongeul/src/components/shared-diary/atoms/RecentAuthor.tsx
  mongeul/src/components/shared-diary/molecules/CodeModalContent.tsx
  mongeul/src/components/shared-diary/molecules/FriendPlusModalContent.tsx
  mongeul/src/components/shared-diary/molecules/SharedDiaryCard.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryHeader.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryList.tsx
  mongeul/src/lib/api/auth.ts
Labels: 🌈 FE, 💫 feat

#40 Feature/37 setting
  mongeul/src/app/globals.css
  mongeul/src/app/layout.tsx
  mongeul/src/app/setting/@detail/diary-lock/page.tsx
  mongeul/src/app/setting/@detail/font/page.tsx
  mongeul/src/app/setting/@detail/nickname/page.tsx
  mongeul/src/app/setting/@detail/theme/page.tsx
  mongeul/src/app/setting/default.tsx
  mongeul/src/app/setting/page.tsx
  mongeul/src/components/common/atoms/Card.tsx
  mongeul/src/components/common/atoms/Input.tsx
  mongeul/src/components/common/molecules/DiaryLockInput.tsx
  mongeul/src/components/layout/ParellelLayout.tsx
  mongeul/src/components/setting/atoms/Line.tsx
  mongeul/src/components/setting/atoms/RadioButton.tsx
  mongeul/src/components/setting/atoms/Slider.tsx
  mongeul/src/components/setting/atoms/Text.tsx
  mongeul/src/components/setting/atoms/ThemeButton.tsx
  mongeul/src/components/setting/atoms/Title.tsx
  mongeul/src/components/setting/molecules/CategoryCard.tsx
  mongeul/src/components/setting/molecules/FontSelect.tsx
  mongeul/src/components/setting/molecules/FontSelectList.tsx
  mongeul/src/components/setting/molecules/FontSizeController.tsx
  mongeul/src/components/setting/molecules/ThemeSelect.tsx
  mongeul/src/components/setting/molecules/ThemeSelectList.tsx
  mongeul/src/components/setting/organisms/FontPreviewCard.tsx
  mongeul/src/components/setting/organisms/FontSelectCard.tsx
  mongeul/src/components/setting/organisms/ThemeSelectCard.tsx
  mongeul/src/components/setting/templates/DiaryLockTemplates.tsx
  mongeul/src/components/setting/templates/FontTemplates.tsx
  mongeul/src/components/setting/templates/NicknameTemplates.tsx
  mongeul/src/components/setting/templates/SettingTemplates.tsx
  mongeul/src/components/setting/templates/ThemeTemplates.tsx
  mongeul/src/components/write-diary/molecules/FeelingsSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/context/ThemeContext.tsx
  mongeul/src/lib/theme.ts
  mongeul/src/types/settingTypes.ts
  mongeul/tailwind.config.ts
Labels: 🌈 FE, 🐛 bug, 💫 feat

#41 Feature/28 calendar
  mongeul/.vscode/settings.json
  mongeul/src/app/diary/page.tsx
  mongeul/src/components/calendar/atoms/CalendarDate.tsx
  mongeul/src/components/calendar/atoms/CalendarHeader.tsx
  mongeul/src/components/calendar/atoms/CalendarIcon.tsx
  mongeul/src/components/calendar/molecules/CalendarGrid.tsx
  mongeul/src/components/calendar/molecules/CalendarRow.tsx
  mongeul/src/components/calendar/organisms/Calendar.tsx
  mongeul/src/components/diary/atoms/DiaryContent.tsx
  mongeul/src/components/diary/atoms/DiaryDate.tsx
  mongeul/src/components/diary/atoms/DiaryDisclosure.tsx
  mongeul/src/components/diary/atoms/DiaryImage.tsx
  mongeul/src/components/diary/atoms/DiaryTitle.tsx
  mongeul/src/components/diary/atoms/DiaryWeather.tsx
  mongeul/src/components/diary/molecules/DiaryHeader.tsx
  mongeul/src/components/diary/organisms/Diary.tsx
  mongeul/src/lib/api/diary.ts
  mongeul/src/store/calendarSlice.ts
  mongeul/src/store/store.ts
  mongeul/src/types/diaryTypes.ts
Labels: 🌈 FE, 💫 feat

#44 Feature/36 writediarypost
  mongeul/src/actions/diary/createDiary.ts
  mongeul/src/app/api/diary/create-diary/route.ts
  mongeul/src/app/api/diary/read-diary/route.ts
  mongeul/src/app/layout.tsx
  mongeul/src/app/setting/layout.tsx
  mongeul/src/app/write-diary/page.tsx
  mongeul/src/components/diary/atoms/DiaryDate.tsx
  mongeul/src/components/diary/atoms/DiaryDisclosure.tsx
  mongeul/src/components/diary/atoms/DiaryPrivateStatus.tsx
  mongeul/src/components/diary/molecules/DiaryHeader.tsx
  mongeul/src/components/layout/DefaultLayout.tsx
  mongeul/src/components/layout/ParellelLayout.tsx
  mongeul/src/components/navbar/atoms/WriteButton.tsx
  mongeul/src/components/navbar/atoms/WriteButtonDetail.tsx
  mongeul/src/components/navbar/molecules/DefaultNavBar.tsx
  mongeul/src/components/navbar/organisms/NavBar.tsx
  mongeul/src/components/setting/molecules/FontSizeController.tsx
  mongeul/src/components/write-diary/molecules/DisclosureSelect.tsx
  mongeul/src/components/write-diary/molecules/DrawingNavBar.tsx
  mongeul/src/components/write-diary/molecules/FeelingsSelect.tsx
  mongeul/src/components/write-diary/molecules/PrivateStatusSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/Canvas.tsx
  mongeul/src/components/write-diary/organisms/DrawingCard.tsx
  mongeul/src/components/write-diary/organisms/IconCard.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/templates/DrawingForm.tsx
  mongeul/src/lib/api/diary.ts
  mongeul/src/store/calendarSlice.ts
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/drawingSlice.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/utils/stateRef.ts
  mongeul/src/utils/uiUtils.tsx
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#49 Feature/48 loginlayout
  mongeul/src/app/(is-login)/diary/page.tsx
  mongeul/src/app/(is-login)/feed/page.tsx
  mongeul/src/app/(is-login)/layout.tsx
  mongeul/src/app/(is-login)/notification/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/diary-lock/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/font/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/nickname/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/theme/page.tsx
  mongeul/src/app/(is-login)/setting/default.tsx
  mongeul/src/app/(is-login)/setting/layout.tsx
  mongeul/src/app/(is-login)/setting/page.tsx
  mongeul/src/app/(is-login)/shared-diary/page.tsx
  mongeul/src/app/(is-login)/write-diary/drawing/page.tsx
  mongeul/src/app/(is-login)/write-diary/layout.tsx
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/app/layout.tsx
  mongeul/src/assets/icons/feeling.svg
  mongeul/src/components/common/atoms/FeelingsIcon.tsx
  mongeul/src/components/common/atoms/Input.tsx
  mongeul/src/components/common/atoms/PrivateStatusIcon.tsx
  mongeul/src/components/common/atoms/Textarea.tsx
  mongeul/src/components/common/atoms/WeatherIcon.tsx
  mongeul/src/components/diary/atoms/DiaryPrivateStatus.tsx
  mongeul/src/components/write-diary/molecules/FeelingsSelect.tsx
  mongeul/src/components/write-diary/molecules/PrivateStatusSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/organisms/ContentCard.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/TitleCard.tsx
  mongeul/src/utils/uiUtils.tsx
Labels: 🌈 FE, 🐛 bug, 💫 feat

#52 Feature/24 login
  mongeul/src/app/auth/login/page.tsx
  mongeul/src/app/auth/nickname-setting/page.tsx
  mongeul/src/components/auth/molecules/NicknameModal.tsx
  mongeul/src/components/auth/molecules/SocialLoginButtons.tsx
  mongeul/src/components/shared-diary/atoms/NicknameBadge.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/auth.ts
  mongeul/src/store/store.ts
  mongeul/src/store/userSlice.ts
Labels: 🌈 FE, 💫 feat

#56 Feature/45 writetemp
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/actions/diary/createDiary.ts
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/assets/icons/feel.svg
  mongeul/src/components/common/atoms/FeelingsIcon.tsx
  mongeul/src/components/write-diary/atoms/BackButton.tsx
  mongeul/src/components/write-diary/molecules/FeelingSelect.tsx
  mongeul/src/components/write-diary/molecules/TempAlertModal.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/IconCard.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/drawingSlice.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/types/drawingTypes.ts
Labels: 🌈 FE, 💫 feat

#57 Feature/55 header
  mongeul/src/assets/icons/back.svg
  mongeul/src/components/header/atoms/BackButton.tsx
  mongeul/src/components/header/atoms/NotificationButton.tsx
  mongeul/src/components/header/molecules/MobileHeader.tsx
  mongeul/src/components/header/molecules/WebHeader.tsx
  mongeul/src/components/header/orgamisms/Header.tsx
  mongeul/src/components/layout/ParellelLayout.tsx
  mongeul/src/components/setting/molecules/FontSizeController.tsx
  mongeul/src/components/setting/organisms/FontSelectCard.tsx
  mongeul/src/context/ThemeContext.tsx
Labels: 🌈 FE, 💫 feat
