Repository mongeul/mongeulmongeul, pull requests merged in 2025-04, with the labels that each got.

#111 feat: 그림 이미지 업로드 google drive -> cloudinary 변경(업로드, 수정, 삭제 로직 수정)
  mongeul/src/main/java/com/specup/mongeul/domain/diary/service/DiaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/service/ShareDiaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/service/CloudinaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/service/GoogleDriveService.java
Labels: 🔥 BE, 💫 feat, ♻️ refactoring

#116 feat: 알림페이지 토큰 생성
  mongeul/.gitignore
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/app/(is-login)/notification/page.tsx
  mongeul/src/lib/firebase-client.ts
  mongeul/src/lib/firebasse-admin.ts
  mongeul/src/utils/getFcmToken.ts
Labels: 🌈 FE, 💫 feat

#117 Refactor/81 writediary
  .DS_Store
  mongeul/public/icons/icon-1024x1024.png
  mongeul/public/icons/icon-192x192.png
  mongeul/public/manifest.json
  mongeul/src/assets/images/angry.png
  mongeul/src/assets/images/basic.png
  mongeul/src/assets/images/cloudy.png
  mongeul/src/assets/images/happy.png
  mongeul/src/assets/images/lock.png
  mongeul/src/assets/images/private.png
  mongeul/src/assets/images/public.png
  mongeul/src/assets/images/rainy.png
  mongeul/src/assets/images/sad.png
  mongeul/src/assets/images/snowy.png
  mongeul/src/assets/images/soso.png
  mongeul/src/assets/images/sunny.png
  mongeul/src/assets/images/text_logo.png
  mongeul/src/assets/images/wow.png
  mongeul/src/components/common/atoms/Bubble.tsx
  mongeul/src/components/common/atoms/DiaryFeelingIcon.tsx
  mongeul/src/components/common/atoms/DiaryImageCard.tsx
  mongeul/src/components/common/atoms/DiaryPrivateStatusIcon.tsx
  mongeul/src/components/common/atoms/DiaryWeatherIcon.tsx
  mongeul/src/components/common/atoms/FeelingsIcon.tsx
  mongeul/src/components/common/atoms/ImageCard.tsx
  mongeul/src/components/common/atoms/PrivateStatusIcon.tsx
  mongeul/src/components/common/atoms/WeatherIcon.tsx
  mongeul/src/components/common/molecules/DiaryHeader.tsx
  mongeul/src/components/common/organisms/DiaryDetailContainer.tsx
  mongeul/src/components/diary/atoms/DiaryPrivateStatus.tsx
  mongeul/src/components/diary/atoms/DiaryWeather.tsx
  mongeul/src/components/feed/atoms/FeedEmojiButton.tsx
  mongeul/src/components/feed/atoms/FeedLikeButton.tsx
  mongeul/src/components/feed/atoms/FeedListItem.tsx
  mongeul/src/components/header/atoms/NotificationButton.tsx
  mongeul/src/components/header/molecules/WebHeader.tsx
  mongeul/src/components/navbar/atoms/LinkPersonalDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDraftButton.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/FeelingSelect.tsx
  mongeul/src/components/write-diary/molecules/PrivateStatusSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/useDiarySaveStatus.ts
  mongeul/src/types/diaryTypes.ts
Labels: 🌈 FE, 🐛 bug, ♻️ refactoring

#119 fix: snowy 이미지 import 수정
  mongeul/src/components/common/atoms/WeatherIcon.tsx
Labels: 🌈 FE, 🐛 bug

#120 Feature/32 sharediary
  mongeul/src/app/(is-login)/shared-diary/[id]/@detail/page.tsx
  mongeul/src/app/(is-login)/shared-diary/[id]/layout.tsx
  mongeul/src/components/shared-diary/templates/SharedDiaryTemplate.tsx
Labels: 🌈 FE, 💫 feat

#124 Feature/32 sharediary
  mongeul/src/app/(is-login)/shared-diary/[id]/layout.tsx
  mongeul/src/components/layout/ClientLayout.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryContent.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryDate.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryImage.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryTitle.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryWeather.tsx
  mongeul/src/components/shared-diary/molecules/ShareDiaryDetailHeader.tsx
  mongeul/src/components/shared-diary/molecules/SharedDiaryCard.tsx
  mongeul/src/components/shared-diary/organisms/ShareDiary.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryPreview.tsx
  mongeul/src/components/shared-diary/templates/ShareDiaryDetailTemplate.tsx
  mongeul/src/components/shared-diary/templates/SharedDiaryTemplate.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/auth.ts
  mongeul/src/store/calendarSlice.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#125 Feature/114 alarm
  mongeul/src/lib/firebase-admin.ts
  mongeul/src/lib/firebase-client.ts
  mongeul/src/utils/getFcmToken.ts
Labels: 🌈 FE, ♻️ refactoring

#128 feat: 일기 미리보기 감정 추가
  mongeul/src/components/diary/atoms/DiaryFeeling.tsx
  mongeul/src/components/diary/atoms/DiaryPrivateStatus.tsx
  mongeul/src/components/diary/atoms/DiaryWeather.tsx
  mongeul/src/components/diary/molecules/DiaryHeader.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
  mongeul/src/store/calendarSlice.ts
Labels: 🌈 FE, 💫 feat

#130 feat: 달력 아이콘 변경, 웹 이미지 추가
  mongeul/src/components/calendar/atoms/CalendarDate.tsx
  mongeul/src/components/calendar/atoms/CalendarIcon.tsx
  mongeul/src/components/calendar/molecules/CalendarGrid.tsx
  mongeul/src/components/calendar/organisms/Calendar.tsx
  mongeul/src/components/diary/atoms/DiaryDate.tsx
  mongeul/src/components/diary/atoms/DiaryImage.tsx
  mongeul/src/components/diary/organisms/Diary.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
  mongeul/src/store/calendarSlice.ts
Labels: 🌈 FE, 💫 feat

#131 Feature/127 feedcomment
  mongeul/src/assets/icons/comment-write.svg
  mongeul/src/components/common/atoms/ConfirmModal.tsx
  mongeul/src/components/feed/atoms/FeedCommentButton.tsx
  mongeul/src/components/feed/molecules/CommentInput.tsx
  mongeul/src/components/feed/molecules/CommentItem.tsx
  mongeul/src/components/feed/organisms/CommentList.tsx
  mongeul/src/components/feed/organisms/CommentModal.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/lib/api/comment.ts
  mongeul/src/utils/formatDate.ts
Labels: 🌈 FE, 💫 feat

#135 refactor: 공유일기 달력 아이콘 변경
  mongeul/src/components/auth/molecules/SocialLoginButtons.tsx
  mongeul/src/components/calendar/molecules/ShareCalendarGrid.tsx
  mongeul/src/components/feed/molecules/CommentInput.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryFeeling.tsx
  mongeul/src/components/shared-diary/atoms/ShareDiaryWeather.tsx
  mongeul/src/components/shared-diary/molecules/ShareDiaryDetailHeader.tsx
  mongeul/src/components/shared-diary/templates/SharedDiaryTemplate.tsx
  mongeul/src/store/calendarSlice.ts
  mongeul/src/store/shareDiarySlice.ts
Labels: 🌈 FE, ♻️ refactoring

#136 Refactor/133 feed
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/actions/write-diary.ts
  mongeul/src/components/feed/atoms/FeedEmojiCountButton.tsx
  mongeul/src/components/feed/atoms/FeedListItem.tsx
  mongeul/src/components/feed/molecules/FeedList.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/store/feedSlice.ts
Labels: 🌈 FE, ♻️ refactoring

#137 feat: 웹 일기 수정삭제 버튼 / 아이콘 위치 수정
  mongeul/src/components/diary/atoms/DiaryImage.tsx
  mongeul/src/components/diary/molecules/DiaryHeader.tsx
  mongeul/src/components/diary/organisms/Diary.tsx
  mongeul/src/components/diary/templates/DiaryDetailTemplate.tsx
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#139 design: 모바일 프리뷰 수정
  mongeul/src/components/calendar/atoms/CalendarIcon.tsx
  mongeul/src/components/calendar/molecules/CalendarGrid.tsx
  mongeul/src/components/diary/organisms/DiaryPreview.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryPreview.tsx
Labels: 🌈 FE, ♻️ refactoring
