Repository mongeul/mongeulmongeul, pull requests merged in 2025-03, with the labels that each got.

#61 Feature/54 writecalendar
  mongeul/src/actions/diary/createDiary.ts
  mongeul/src/actions/write-diary.ts
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/components/common/atoms/LinkButton.tsx
  mongeul/src/components/write-diary/atoms/BackButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDraftButton.tsx
  mongeul/src/components/write-diary/atoms/DraftItem.tsx
  mongeul/src/components/write-diary/atoms/DraftListButton.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/DraftButtons.tsx
  mongeul/src/components/write-diary/molecules/DraftList.tsx
  mongeul/src/components/write-diary/molecules/TempAlertModal.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/DraftListModal.tsx
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/store/diarySlice.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/tailwind.config.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#64 Feature/32 sharediary
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/app/auth/login/page.tsx
  mongeul/src/components/auth/molecules/NicknameModal.tsx
  mongeul/src/components/shared-diary/molecules/FriendConfirmModal.tsx
  mongeul/src/components/shared-diary/molecules/FriendPlusModal.tsx
  mongeul/src/components/shared-diary/molecules/SharedDiaryCard.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryHeader.tsx
  mongeul/src/components/shared-diary/organisms/SharedDiaryList.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/auth.ts
  mongeul/src/lib/api/sharediary.ts
  mongeul/src/store/shareDiarySlice.ts
  mongeul/src/store/store.ts
Labels: 🌈 FE, 💫 feat

#68 Feature/28 diary
  mongeul/package-lock.json
  mongeul/src/app/(is-login)/diary/page.tsx
  mongeul/src/components/calendar/molecules/CalendarGrid.tsx
  mongeul/src/components/calendar/organisms/Calendar.tsx
  mongeul/src/components/common/molecules/DiaryLockInput.tsx
  mongeul/src/components/diary/atoms/DiaryDate.tsx
  mongeul/src/components/diary/atoms/DiaryPrivateStatus.tsx
  mongeul/src/components/diary/atoms/DiaryWeather.tsx
  mongeul/src/components/diary/molecules/DiaryHeader.tsx
  mongeul/src/components/diary/organisms/Diary.tsx
  mongeul/src/lib/api/diary.ts
  mongeul/src/store/calendarSlice.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#69 Feature/67 feeddetail
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/src/actions/feed.ts
  mongeul/src/app/(is-login)/feed/@detail/[id]/page.tsx
  mongeul/src/components/common/atoms/DiaryContentCard.tsx
  mongeul/src/components/common/atoms/DiaryDate.tsx
  mongeul/src/components/common/atoms/DiaryFeelingIcon.tsx
  mongeul/src/components/common/atoms/DiaryPrivateStatusIcon.tsx
  mongeul/src/components/common/atoms/DiaryTitle.tsx
  mongeul/src/components/common/atoms/DiaryWeatherIcon.tsx
  mongeul/src/components/common/atoms/ImageCard.tsx
  mongeul/src/components/common/molecules/DiaryHeader.tsx
  mongeul/src/components/common/organisms/DiaryDetailContainer.tsx
  mongeul/src/components/feed/atoms/FeedListItem.tsx
  mongeul/src/components/feed/molecules/FeedList.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/lib/api/feed.ts
  mongeul/src/types/feedTypes.ts
Labels: 🌈 FE, 💫 feat

#73 Feature/70 updatediary
  mongeul/src/actions/write-diary.ts
  mongeul/src/app/(is-login)/diary/page.tsx
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/app/(is-login)/write-diary/picture/page.tsx
  mongeul/src/assets/icons/menu.svg
  mongeul/src/components/common/atoms/DiaryContentCard.tsx
  mongeul/src/components/common/atoms/DiaryDate.tsx
  mongeul/src/components/navbar/atoms/LinkPersonalDiaryButton.tsx
  mongeul/src/components/navbar/atoms/LinkSharedDiaryButton.tsx
  mongeul/src/components/navbar/atoms/LinkWriteButton.tsx
  mongeul/src/components/navbar/molecules/DefaultNavBar.tsx
  mongeul/src/components/navbar/organisms/NavBar.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDraftButton.tsx
  mongeul/src/components/write-diary/atoms/DraftItem.tsx
  mongeul/src/components/write-diary/atoms/DraftListButton.tsx
  mongeul/src/components/write-diary/molecules/BrushSelectPalette.tsx
  mongeul/src/components/write-diary/molecules/BrushSizePalette.tsx
  mongeul/src/components/write-diary/molecules/ColorPalette.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/DraftList.tsx
  mongeul/src/components/write-diary/molecules/PictureNavBar.tsx
  mongeul/src/components/write-diary/molecules/UndoRedoButtons.tsx
  mongeul/src/components/write-diary/organisms/DrawingCard.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/organisms/PictureCard.tsx
  mongeul/src/components/write-diary/organisms/PictureToolCard.tsx
  mongeul/src/components/write-diary/templates/PictureForm.tsx
  mongeul/src/components/write-diary/templates/WriteForm.tsx
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/store/diarySlice.ts
  mongeul/src/store/pictureSlice.ts
  mongeul/src/store/store.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/types/drawingTypes.ts
  mongeul/src/types/pictureTypes.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#75 Feature/32 sharediary
  mongeul/src/app/auth/login/page.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/auth.ts
Labels: 🌈 FE, 💫 feat

#77 Feature/74 feedemoji
  mongeul/next.config.ts
  mongeul/src/actions/feed.ts
  mongeul/src/actions/write-diary.ts
  mongeul/src/assets/icons/comment.svg
  mongeul/src/assets/icons/like.svg
  mongeul/src/components/common/atoms/Bubble.tsx
  mongeul/src/components/common/atoms/Button.tsx
  mongeul/src/components/common/atoms/Card.tsx
  mongeul/src/components/common/atoms/FeelingsIcon.tsx
  mongeul/src/components/common/atoms/ImageCard.tsx
  mongeul/src/components/common/atoms/WeatherIcon.tsx
  mongeul/src/components/feed/atoms/FeedCommentButton.tsx
  mongeul/src/components/feed/atoms/FeedEmojiButton.tsx
  mongeul/src/components/feed/atoms/FeedEmojiCountButton.tsx
  mongeul/src/components/feed/atoms/FeedLikeButton.tsx
  mongeul/src/components/feed/molecules/FeedEmojiBubble.tsx
  mongeul/src/components/feed/molecules/FeedEmojiGroup.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/components/write-diary/atoms/DraftItem.tsx
  mongeul/src/components/write-diary/molecules/FeelingSelect.tsx
  mongeul/src/components/write-diary/molecules/PrivateStatusSelect.tsx
  mongeul/src/components/write-diary/molecules/WeatherSelect.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/PictureCard.tsx
  mongeul/src/lib/api/feed.ts
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/store/feedSlice.ts
  mongeul/src/types/diaryTypes.ts
  mongeul/src/types/feedTypes.ts
  mongeul/src/types/pictureTypes.ts
  mongeul/src/utils/getEmojiId.ts
  mongeul/tailwind.config.ts
Labels: 🌈 FE, 💫 feat

#79 Feature/78 diaryhandling
  mongeul/src/actions/write-diary.ts
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/components/feed/molecules/FeedEmojiGroup.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/components/navbar/atoms/LinkPersonalDiaryButton.tsx
  mongeul/src/components/navbar/atoms/LinkWriteButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDraftButton.tsx
  mongeul/src/components/write-diary/atoms/DraftItem.tsx
  mongeul/src/components/write-diary/molecules/UpdateAlertModal.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/PictureCard.tsx
  mongeul/src/components/write-diary/templates/WriteForm.tsx
  mongeul/src/store/diarySlice.ts
  mongeul/src/utils/convertLinesToImage.ts
Labels: 🌈 FE, 🐛 bug, 💫 feat

#84 Feature/80 loadingui
  mongeul/eslint.config.mjs
  mongeul/next.config.ts
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/public/fonts/NanumSquareRoundR.ttf
  mongeul/public/fonts/RixXladywatermelonR.ttf
  mongeul/public/fonts/SejongGeulggot 2.ttf
  mongeul/src/actions/feed.ts
  mongeul/src/app/(is-login)/feed/layout.tsx
  mongeul/src/app/(is-login)/setting/@detail/font/page.tsx
  mongeul/src/app/(is-login)/setting/@detail/theme/page.tsx
  mongeul/src/app/(is-login)/setting/layout.tsx
  mongeul/src/app/(is-login)/write-diary/page.tsx
  mongeul/src/app/globals.css
  mongeul/src/app/layout.tsx
  mongeul/src/assets/icons/check.svg
  mongeul/src/components/common/atoms/CheckBox.tsx
  mongeul/src/components/common/atoms/DiaryContentCard.tsx
  mongeul/src/components/common/atoms/Spinner.tsx
  mongeul/src/components/common/organisms/DiaryDetailContainer.tsx
  mongeul/src/components/feed/molecules/FeedList.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/components/layout/ParellelLayout.tsx
  mongeul/src/components/layout/SearchParamsProvider.tsx
  mongeul/src/components/setting/atoms/Title.tsx
  mongeul/src/components/setting/molecules/CategoryCard.tsx
  mongeul/src/components/setting/molecules/FontSelectList.tsx
  mongeul/src/components/setting/organisms/FontPreviewCard.tsx
  mongeul/src/components/setting/organisms/ThemePreviewCard.tsx
  mongeul/src/components/setting/templates/SettingTemplates.tsx
  mongeul/src/components/setting/templates/ThemeTemplates.tsx
  mongeul/src/components/skeletons/DiaryDetailSkeleton.tsx
  mongeul/src/components/skeletons/index.ts
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/molecules/BrushSelectPalette.tsx
  mongeul/src/components/write-diary/molecules/DiarySubmitSpinner.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/DateInputCard.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/templates/WriteForm.tsx
  mongeul/src/context/ThemeContext.tsx
  mongeul/src/types/pictureTypes.ts
  mongeul/src/types/settingTypes.ts
Labels: 🌈 FE, 🐛 bug, 💫 feat

#85 feat: 다이어리 라우트 설정
  mongeul/src/app/(is-login)/diary/@detail/[id]/page.tsx
  mongeul/src/app/(is-login)/diary/@detail/page.tsx
  mongeul/src/app/(is-login)/diary/layout.tsx
  mongeul/src/app/(is-login)/diary/page.tsx
  mongeul/src/components/diary/organisms/Diary.tsx
  mongeul/src/components/diary/organisms/LockDiary.tsx
  mongeul/src/components/diary/templates/DiaryDetailTemplate.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
Labels: 🌈 FE, 💫 feat

#88 Feature/86 writefeedapi
  mongeul/src/actions/feed.ts
  mongeul/src/actions/write-diary.ts
  mongeul/src/components/feed/atoms/FeedEmojiCountButton.tsx
  mongeul/src/components/feed/atoms/FeedListItem.tsx
  mongeul/src/components/feed/molecules/FeedEmojiBubble.tsx
  mongeul/src/components/feed/molecules/FeedList.tsx
  mongeul/src/components/feed/templates/FeedDetailTemplates.tsx
  mongeul/src/components/feed/templates/FeedListTemplates.tsx
  mongeul/src/components/navbar/atoms/LinkPersonalDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDiaryButton.tsx
  mongeul/src/components/write-diary/atoms/CreateDraftButton.tsx
  mongeul/src/components/write-diary/atoms/DraftItem.tsx
  mongeul/src/components/write-diary/atoms/DraftListButton.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/WriteDiaryNavBar.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/organisms/PictureCard.tsx
  mongeul/src/lib/api/apiClient.ts
  mongeul/src/lib/api/feed.ts
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/types/feedTypes.ts
Labels: 🌈 FE, 💫 feat

#95 feat: 모바일 상세
  mongeul/src/components/diary/organisms/DiaryDetail.tsx
  mongeul/src/components/diary/organisms/LockDiary.tsx
  mongeul/src/components/diary/templates/DiaryDetailTemplate.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
  mongeul/src/lib/api/diary.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#99 feat: 모바일 잠금일기 확인
  mongeul/src/app/(is-login)/diary/@detail/[id]/page.tsx
  mongeul/src/components/diary/organisms/DiaryDetail.tsx
  mongeul/src/components/diary/organisms/LockDiary.tsx
  mongeul/src/components/diary/templates/DiaryDetailTemplate.tsx
  mongeul/src/components/diary/templates/DiaryTemplate.tsx
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#100 Feature/97 pwa
  mongeul/next-pwa.d.ts
  mongeul/next.config.ts
  mongeul/package-lock.json
  mongeul/package.json
  mongeul/public/icons/icon-192x192.png
  mongeul/public/manifest.json
  mongeul/src/app/layout.tsx
  mongeul/src/components/common/atoms/ImageCard.tsx
  mongeul/src/components/navbar/molecules/WriteSharedDiaryFriendList.tsx
  mongeul/src/components/navbar/organisms/WriteSharedDIaryModal.tsx
  mongeul/src/lib/api/write-diary.ts
  mongeul/src/types/diaryTypes.ts
Labels: 🌈 FE, 💫 feat

#105 Feature/103 updatediarybutton
  mongeul/src/assets/icons/diary-update.svg
  mongeul/src/components/diary/atoms/DiaryDeleteButton.tsx
  mongeul/src/components/diary/atoms/DiaryUpdateButton.tsx
  mongeul/src/components/diary/molecules/DiaryControlButtons.tsx
  mongeul/src/components/diary/organisms/DiaryDetail.tsx
  mongeul/src/components/navbar/atoms/LinkPersonalDiaryButton.tsx
  mongeul/src/components/write-diary/molecules/DraftAlertModal.tsx
  mongeul/src/components/write-diary/molecules/PictureNavBar.tsx
  mongeul/src/components/write-diary/organisms/KonvaCanvas.tsx
  mongeul/src/components/write-diary/organisms/PictureCard.tsx
  mongeul/src/store/pictureSlice.ts
  mongeul/src/store/store.ts
  mongeul/src/utils/stateRef.ts
Labels: 🌈 FE, 💫 feat, ♻️ refactoring

#107 Refactor/106 refactor
  mongeul/src/main/java/com/specup/mongeul/domain/diary/controller/DiaryController.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/controller/ShareDiaryController.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/entity/Diary.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/repository/DiaryRepository.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/repository/ShareDiaryRepository.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/service/DiaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/diary/service/ShareDiaryService.java
  mongeul/src/main/java/com/specup/mongeul/domain/diaryemoji/controller/DiaryEmojiController.java
  mongeul/src/main/java/com/specup/mongeul/domain/diaryemoji/service/DiaryEmojiService.java
  mongeul/src/main/java/com/specup/mongeul/domain/service/GoogleDriveController.java
  mongeul/src/main/java/com/specup/mongeul/domain/service/GoogleDriveService.java
  mongeul/src/test/java/mongeul/diary/data/DataInitializer.java
  mongeul/src/test/java/mongeul/diary/repository/DiaryRepositoryTest.java
Labels: 🔥 BE, ♻️ refactoring, 💩 cleanup
